### ISSUE TITLE
Implement Persistent store for mobile / desktop apps

### ISSUE THREAD

**Issue by simonferquel** [launchdarkly/dotnet-client#37]
On a desktop scenario, if the user launch the app while not connected to Internet, even if he has already launched the app in a previous session, feature flags cannot be evaluated.
This is especially annoying when the polling interval is increased (we have a desktop app with 100k+ users, and the default 1s polling interval is a bit short imo).

We could make IFeatureStore public, and make the InMemoryFeatureStore overridable to implement persistence. We should also modify the way the client considers it is initialized so that it could rely on persisted data when temporary offline.

I'll make a pull request implementing that.

**Comment by drichelson** [comment]
@simonferquel Thanks for the feedback (and I see the PR). This SDK is not suitable for desktop/mobile environments for security reasons. Using it in an environment where an end user could view the contents of the Feature Store potentially exposes sensitive information.

We take a different approach for web/mobile/desktop. Check out our [ios](https://github.com/launchdarkly/ios-client) and [Android](https://github.com/launchdarkly/android-client) SDKs for example implementations.

It's probably best to continue this conversation via support@launchdarkly.com. Please email us there and we can figure out how to best address your needs.

**Comment by simonferquel** [comment]
I have to say I strongly disagree with that. Giving access to the feature flags / rules to my users does not seem a security issue to me. The worst that could happen would be some advanced users opting-in for beta features instead of being given access by a rule.

Offline support is more important to me.

In case you don't want this feature in the official codebase, are you ok for us to maintain a fork behaving like this ?

**Comment by arun251** [comment]
Hi @simonferquel , please email support@launchdarkly.com so we can have a conversation about this.

**Comment by StephenCleary** [comment]
This is also an important issue for us. It's probably best to discuss it here, where other pre-sales people can see the resolution.

For our product, offline access (to the real values) is _necessary_ for the iOS/Android SDKs, is nice-to-have for this .NET SDK, and not needed for the JavaScript (browser) SDK.

**Comment by ISkomorokh** [comment]
@StephenCleary I'm glad to see you here! It would be awesome if you could spend some time to review .net SDK async part.

Sorry for off topic
