### ISSUE TITLE
.NET SDK 5.0+ LdClient Constructor Crash

### ISSUE THREAD

**Issue by acrabb** [launchdarkly/dotnet-client#92]
We're using the .net SDK in our Xamarin app. Updating from 3.3.2 to 4.1.1 had no issues.

Updating from 4.1.1 to 5.0.0 throws this runtime exception:
> ```System.MethodAccessException: Method `LaunchDarkly.Common.ClientEnvironment..ctor()' is inaccessible from method `LaunchDarkly.Client.ServerSideClientEnvironment..ctor()'```.

at the `LdClient` constructor:
> `client = new LdClient (sdkKey);`

```{MvvmCross.Platform.Exceptions.MvxException: Problem creating viewModel of type LaunchScreenViewModel ---> MvvmCross.Platform.Exceptions.MvxIoCResolveException: Failed to construct FeatureFlagManagerIos ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'LaunchDarkly.Client.ServerSideClientEnvironment' threw an exception. ---> System.MethodAccessException: Method `LaunchDarkly.Common.ClientEnvironment..ctor()' is inaccessible from method `LaunchDarkly.Client.ServerSideClientEnvironment..ctor()'
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_throw_method_access(intptr,intptr)
  at LaunchDarkly.Client.ServerSideClientEnvironment..ctor () [0x00000] in <48f014d682eb4ebfb747da923046c254>:0 
  at LaunchDarkly.Client.ServerSideClientEnvironment..cctor () [0x00000] in <48f014d682eb4ebfb747da923046c254>:0 
   --- End of inner exception stack trace ---
  at LaunchDarkly.Client.LdClient..ctor (LaunchDarkly.Client.Configuration config) [0x00000] in <48f014d682eb4ebfb747da923046c254>:0 ```

**Comment by acrabb** [comment]
Thanks Eli.
We're using Xamarin for mobile and definitely interested in trying the Xamarin SDK when its ready 👍

**Comment by acrabb** [comment]
Hi @eli-darkly , just checking in on this.

How is the beta Xamarin release going?
How can we help speed along its release-ready development?

**Comment by acrabb** [comment]
@eli-darkly any update here to when the Xamarin SDK will be ready for use?
Cheers.

**Comment by eli-darkly** [comment]
I'm going to close the original issue because Xamarin isn't a supported use for the server-side .NET SDK, but I've passed your contact information to the PM who will be sending out information whenever we get closer to a Xamarin release.
