### ISSUE TITLE
Lambda IOException

### ISSUE THREAD

**Issue by ngcbassman** [launchdarkly/dotnet-client#93]
We are using LaunchDarkly.Client .NET 5.4.0 with AWS Lambdas. 
Sometimes we are receiving this exception while running the lambdas, but we don't know why.

```
{  
   "errorType":"AggregateException",
   "errorMessage":"A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to read data from the transport connection: Operation canceled.)",
   "cause":{  
      "errorType":"IOException",
      "errorMessage":"Unable to read data from the transport connection: Operation canceled.",
      "stackTrace":[  
         "at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)",
         "at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)",
         "at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)",
         "at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)",
         "at System.Net.Http.HttpConnection.FillAsync()",
         "at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)",
         "at System.IO.StreamReader.ReadBufferAsync()",
         "at System.IO.StreamReader.ReadLineAsyncInternal()",
         "at LaunchDarkly.EventSource.EventSourceStreamReader.ReadLineAsync()"
      ],
      "cause":{  
         "errorType":"SocketException",
         "errorMessage":"Operation canceled"
      }
   }
}
```

**Comment by eli-darkly** [comment]
Based on the message about the finalizer thread, it sounds to me like this is only happening at the very end of execution - is that right?

Also, are you calling `Dispose` on the client before you exit?

I haven't seen this happen, but I think I see what it may be talking about. When our streaming connection is shut down, there's some low-level code that is still trying to read the stream. It's normal for it to get an I/O exception at that point. What I'm not sure about is why the exception was "not observed" by any higher-level task. It may be that we have already shut down the rest of the stream-related code at that point and left the failed task in sort of an orphaned state.

I'll have to think about how to test this. I haven't seen it happen when I run .NET code locally; it may be that the Lambda environment is more sensitive to this kind of thing.

**Comment by ngcbassman** [comment]
Maybe that can be a problem, we are using the LdClient as a Singleton, in consideration that Lambdas live for a short period of time and to take advantage of the cache in that period, what do you think, can be the problem?.

**Comment by eli-darkly** [comment]
Well, the client is intended to be used as a singleton - in the normal use case, you would create one during the startup of your application, and dispose of it during shutdown. In a Lambda, that means that it uses up a little of your limited time during startup to establish the connection and get the flag data. But there's really no other option anyway in Lambda, since nothing can persist in between invocations.

**Comment by eli-darkly** [comment]
Are you capturing log output from this lambda and if so, do you see any kind of errors there? I have some ideas about which code in the SDK might be causing this, but they all involve conditions that I would expect to produce some error logging. So if there's nothing in the log, I'll have to rethink my approach.

**Comment by eli-darkly** [comment]
Thanks. That convinces me that I need to look more closely - I did find one problem that could have caused this, which we will definitely fix, but it almost certainly would have produced some error logging so I think there may be another similar issue somewhere else.

In the meantime I would definitely recommend that you try the event handler approach I mentioned above, just as a safety measure. Suppressing unobserved exceptions should not affect anything else, it just means they will not terminate your code. (In .NET 4.5, they do not cause termination, but in .NET 4.0 they do, and it looks like whatever version of .NET Core is supported by Lambda has the same behavior.)

Creating the event handler would look like this - you would do it once at startup time:

```
import System.Threading.Tasks;

TaskScheduler.UnobservedTaskException +=
    (object sender, UnobservedTaskExceptionEventArgs e) =>
    {
        e.SetObserved();
    };
```

**Comment by eli-darkly** [comment]
I'm sorry I didn't update this issue earlier, but if you haven't seen it, the 5.5.0 release of the .NET SDK includes a fix for at least one problem that could have caused unobserved exceptions. If you get a chance, we'd be curious to know whether you still see any of these log errors after upgrading to 5.5.0. I'll close the issue for now but please reopen it if you're still having this problem.
