### ISSUE TITLE
Usage of Ldclient

### ISSUE THREAD

**Issue by celluj34** [launchdarkly/dotnet-client#99]
On the project homepage, you say to create a new instance of the LdClient to access your API: `LdClient ldClient = new LdClient("YOUR_SDK_KEY");`.

What is the intended lifetime of this object? Should I new-up one every time, is it a singleton, is the `httpClient` being used correctly?

I'd like to be able to inject the ILdClient into whatever may need it, so I'm just trying to figure out the best lifetime to use.

**Comment by eli-darkly** [comment]
See the documentation comment for the `LdClient` class: "Applications should instantiate a single `LdClient` for the lifetime of their application."

**Comment by celluj34** [comment]
Perfect. Thank you!
